### PR TITLE
Expose native-tls/vendored feature

### PR DESCRIPTION
**Pull request by aig787**
This PR exposes the already existing `native-tls/vendored` feature to support cross compilation

### CODE REVIEW

**Comment by Marwes** [comment]
You can enable this feature on your own by adding `native-tls/vendored` as a feature in your Cargo.toml so I do not think redis-rs needs to supply this.

**Comment by aig787** [comment]
Yes I found that a little bit after I submitted this and forgot to close. Thanks!

**Comment by BratSinot** [comment]
> You can enable this feature on your own by adding `native-tls/vendored` as a feature in your Cargo.toml so I do not think redis-rs needs to supply this.

Greetings!

I don't get it, how to enable vendored openssl?

**Comment by Marwes** [comment]
> I don't get it, how to enable vendored openssl?

`native-tls = { version = "yourversion", features = ["vendored"] }`

**Comment by BratSinot** [comment]
> > I don't get it, how to enable vendored openssl?
> 
> `native-tls = { version = "yourversion", features = ["vendored"] }`

Hm, for some reason I thought what cargo can't do things like this.

**Pull request closed without merging**
