### PR TITLE
Shutdown connection upon protocol error

### PR DESCRIPTION
**Pull request by arthurprs**
Shutdown connection upon protocol error

Solves #77

### CODE REVIEW

**Comment by badboy** [comment]
LGTM

**Comment by badboy** [comment]
The test is not optimal though. We will always have an `IoError` on the second call, simply because at that point the server is already gone.

**Comment by arthurprs** [comment]
Oh, I see. I'll get to it later today.

**Comment by arthurprs** [comment]
I updated the commit. I reused the library parser to make the test correct.

**Comment by badboy** [comment]
Cool! Don't worrry about the test failure, I'll fix that one and then merge it.

**Comment by badboy** [comment]
Merged as bba92d93ef832a15a631a35b07b487a2f6818017

**Pull request closed without merging**
