### PR TITLE
chore: Fix new clippy warnings on CI

### PR DESCRIPTION
**Pull request by Marwes**

### CODE REVIEW

**Review by weihanglo — APPROVED** [review]
Wow. It's really... clippy 🤪

**Comment by weihanglo** [comment]
Oh no. It still got some errors.

https://travis-ci.org/github/mitsuhiko/redis-rs/jobs/740798275#L1994-L2011

**Comment by Marwes** [comment]
Personally, I think we should just remove clippy. Having CI stable is more important than keeping lints up to date.

**Review by weihanglo — APPROVED** [review]
Great!

**Pull request merged**
