### PR TITLE
ActualConnection: wrap BufReader around TcpStream

### PR DESCRIPTION
**Pull request by astro**
Hi

I am just starting with Rust, and tried to receive messages with this library's experimental Pubsub support. The parser reads byte by byte, performing a lot of syscalls. What's your opinion on using BufReader to reduce the performance impact?

Safety not guaranteed. It still fails for me sometimes with `Invalid byte in response`

### CODE REVIEW

**Comment by astro** [comment]
> It still fails for me sometimes with `Invalid byte in response`

Scratch that. redis kept disconnecting me because the network in between couldn't keep up.

**Comment by mitsuhiko** [comment]
The reason I did not use buf reader is because it did not seem like a good idea to read past what the responses indicate is safe to read.  But I pulled your changes from #63 in.

**Comment by astro** [comment]
Are you concerned about blocking behaviour? I believe if not enough data is available the read from BufStream will return with what's available just like TcpStream.

In my case that detail not relevant because all I'm doing with redis is receiving pubsub notifications at a high rate.

**Comment by xitep** [comment]
today i gave `redis-rs` a try and while i generally like it's api. however, i wondered why it was _that_ slow. after some basic profiling i basically came to the same conclusion as @astro. reading the tcp stream char-by-char is definitely a show-stopper (for me) :(  at least astro's patch gives my program a considerable speed-up.

**Comment by astro** [comment]
FYI: my workload changed from just PubSub to interactive commands as well. I'm running with this patch and it's working fine.

**Comment by mitsuhiko** [comment]
Let's see how this goes.

**Pull request merged**
